version: '3.8'

services:
  gei-frontend:
    build: .
    container_name: gei-frontend
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - gei-backend
    networks:
      - gei-network

  gei-backend:
    build: ./server
    container_name: gei-backend
    ports:
      - "5000:5000"
    volumes:
      - ./server/uploads:/app/uploads
    restart: always
    networks:
      - gei-network

networks:
  gei-network:
    driver: bridge
